### ISSUE TITLE
pprepair dependency on gdal 1.11?

### ISSUE THREAD

**Issue by ldemaz** [tudelft3d/pprepair#22]
Hi! We have built pprepair into software that for various reasons has to use an older version of gdal (1.9.2).  The reason is this: 

OGRFeature::GetGeometryRef() 

Which is in gdal 1.11 but not 1.9.2. 

Is there an earlier version that does not have this dependency, but which is sufficiently robust to incorporate into a production environment?  

Thanks!

**Comment by kenohori** [comment]
There is, but I wouldn't recommend it! The older versions of pprepair don't build with GDAL 1.11, so this might be more trouble than it's worth.

**Comment by ldemaz** [comment]
Thanks!  We managed to figure it out...
