### ISSUE TITLE
How to make Pprepair.sln

### ISSUE THREAD

**Issue by JoFromFrance** [tudelft3d/pprepair#23]
Hello,
 First 1000 sorry for my English and my knowledge( i am a beginner)...
I am doing this tuto : "https://www.dropbox.com/sh/tjsbi6cjb5ui95p/AADQ4pH3JQ7puDBv4sUl6zuGa/pprepair%20installation%20guide.txt?dl=0", 
Everything fine but at the end i have to Open pprepair.sln in Visual Studio.
I made a C++ solution and put in all the files from  "pprepair-master" (https://github.com/tudelft3d/pprepair) and all the files made with Cmake but no compilation is possible (all is in red....).
So how to do this Pprepair.sln
Thanks for all...
Jo from sunny france

**Comment by hugoledoux** [comment]
Bonjour Jo de la France, 

On parle aussi français. Aucune idée où tu as pris ce tutoriel (un lien stp?), mais le fichier *.sln ne vient pas de nous. C'est un fichier qui a été créé par la personne qui a fait le tutoriel. SLN c'est un fichier pour un project visual studio, et nous n'utilisons pas visual studio, ni Windows.

Hugo
