### ISSUE TITLE
segfault when reading features with no geometry

### ISSUE THREAD

**Issue by adrien-berchet-forcity** [tudelft3d/pprepair#41]
Hi,
I had an issue when trying to read some shapefiles in which some features have no geometry (feature->GetGeometryRef() returns 0). It raised a segfault in this case.
I can't make a pull request but just adding this to line 160 solves this issue:
`
      if (!feature->GetGeometryRef()) continue;
`
Regards

**Comment by hugoledoux** [comment]
thanks. But from which branch is this? And out of curiosity, why can't you make a pull request?

**Comment by adrien-berchet-forcity** [comment]
Ups sorry, I meant line 100, not 160. And I did not say it is in the IOWorker.cpp file of the master branch.

For the pull request I have a permission issue: 
ERROR: Permission to tudelft3d/pprepair.git denied to adrien-berchet-forcity.

**Comment by hugoledoux** [comment]
You don't have write permission on our code, that's normal. Create a fork of our code, modify it and the create a pull request https://help.github.com/articles/creating-a-pull-request/

**Comment by adrien-berchet-forcity** [comment]
Indeed, sorry!
I did a PR for that.
