### ISSUE TITLE
Forced region splitting

### ISSUE THREAD

**Issue by benstadin** [tudelft3d/pprepair#45]
Is it possible to force to split regions, preserving all regions, and remove "cutoff regions"?

I give an example below for what I want to achieve. The orange polygons here originally came from layer "B" within a CAD file, the green polygon came from layer "A". The green polygons are actually about the same size as the whole complete area with all it's polygons. So the green area polygon is visible there because there is no orange polygon on top of it. 

So I want to "cut out" just a green polygon as it's visible in the first picture, and throw away the rest of the green polygon since it is mostly overlapped by orange polygons.

Green and orange:
![region_split_example](https://cloud.githubusercontent.com/assets/1433419/17329735/388fb136-58c4-11e6-8959-b7e3cf611653.png)

Only green:
![region_split_example_green](https://cloud.githubusercontent.com/assets/1433419/17329910/fe0fc3e2-58c4-11e6-8fe6-f1343b6f3c44.png)

**Comment by hugoledoux** [comment]
It's possible, but I think you more need a GIS than pprepair to be honest.

In the branch 'new' there's a better version to handle input/output files. What you're looking for is the option PL, for priority list. You'd repair as such

`pprepair -i A.shp -i B.shp -r PL --priority prio.txt`

and have in the same folder a file `prio.txt` which contains 3 lines:
```
datasets
A
B
```

this gives the priority to use when there are overlapping polygons.
